# Generated by Django 3.1.4 on 2021-05-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('contact', models.IntegerField(max_length=12)),
                ('gender', models.CharField(max_length=50)),
                ('father', models.CharField(max_length=100)),
                ('mother', models.CharField(max_length=100)),
                ('sivling', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=50)),
                ('home_town', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50, null=True)),
                ('skill', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('hobbies', models.CharField(max_length=100)),
                ('profile_img', models.ImageField(upload_to='profile')),
                ('document', models.FileField(upload_to='document')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
