# Generated by Django 3.1.4 on 2021-05-15 09:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeupload',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resumeupload',
            name='contact',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='resumeupload',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 15, 9, 28, 24, 975833, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resumeupload',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='resumeupload',
            name='document',
            field=models.FileField(blank=True, upload_to='document'),
        ),
        migrations.AlterField(
            model_name='resumeupload',
            name='education',
            field=models.CharField(choices=[('ITI', 'ITI'), ('Diploma', 'Diploma'), ('B Tech,', 'B Tech.'), ('M Tech', 'M Tech'), ('BA.', 'BA.'), ('BSc.', 'BSc.'), ('BCom.', 'BCom.'), ('Phd.', 'Phd.')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resumeupload',
            name='experience',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='resumeupload',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='resumeupload',
            name='sivling',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resumeupload',
            name='skill',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('Machine Learning', 'Machine Learning'), ('Java', 'Java'), ('Web Developer', 'Web Developer'), ('Web Designer', 'Web Designer'), ('Artificial Intelligent', 'Artificial Intelligent'), ('Deep Learning', 'Deep Learning'), ('Data Science', 'Data Science'), ('Data Analysis', 'Data Analysis'), ('Designer', 'Designer'), ('Tool Designer', 'Tool Designer'), ('Auto CAD', 'Auto CAD'), ('Creo', 'Creo'), ('Catia', 'Catia'), ('NX', 'NX'), ('FEA', 'FEA'), ('Design Engineer', 'Design Engineer'), ('Draftsman', 'Draftsman'), ('Solidwork', 'Solidwork'), ('Programmer', 'Programmer'), ('DelCAM', 'DelCAM')], max_length=100),
        ),
    ]
